apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 30
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      nodeSelector:
        nodepool: karpenter-x86-64
      tolerations:
      - key: architecture
        operator: Equal
        value: x86-64
        effect: NoSchedule
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "600Mi"
            cpu: "1000m"
          limits:
            memory: "800Mi"
            cpu: "1500m"
